import = [
"~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding. x = 10
padding y = 11
decorations = "Buttonless"
opacity = 0.8
option_as_alt = "Both"

[font]
normal. family = "OxProto Nerd Font"

size = 19
